### PR TITLE
First pass of Chisel emissives retexturing

### PR DESCRIPTION
**Pull request by QuantumManiac**
I did a bit of work on adding emissives to various Chisel blocks wherever I saw fit and was possible. While I did retexture a lot of blocks, there are still some remaining that were not retextured either because I didn't know if it needed emissives or due to technical difficulties due to how the textures were made. More on this in their respective sections below.

Here's what this branch has retextured so far, along with some comments about it. 

Shaders, if used in screenshot, is BSL v7.1.04.1, with modified lighting to make light sources a less warm color. MC Version is 1.12.2.

**Antiblocks**

image
This was done in the original version of the resource pack. 

**Futura Blocks**

image
Looks very nice and animations work as intended.

Issues: 
- The following blocks, while rendering perfectly in-world, do not render properly as an inventory item:
"Rainbowliciously Wavy"
"Fabulously Wavy"
"Gray Screen"
"Cyan Screen"
image
Animation [here](https://gfycat.com/briskjampackedasianwaterbuffalo)

Curiously, they do render properly in JEI. I suspect that there's an issue with how the emissive textures overlay over the standard textures or something of the sorts.

**Laboratory Blocks**

image
Only a single block that I thought needed the treatment - "Console". I was thinking of also added emissives to "Left Faced-" and "Right-Faced Arrows", input needed.

**Uranium Blocks**
image
Decided to add a bit of radioactive glow to the uranium blocks. Looks a bit too bright in my opinion though, feedback appreciated.

**Nether Brick**
image
The above is a picture of all four of the "Lava Brick" variants, but it's too dark to differentiate them. Looks good, but the tiling looks a bit awkward when they there's just a single block.

**Factory Blocks**
_(In the \technical folder)_
image
Just added glowing to the "Glowing Vent" block. Would be nice if we could make the emissive look like the glow is leaking out like in the base texture.

**Voidstone**
image

Runes are the only thing I added emissives to for all the voidstone variants.
I tried to add emissives to the animated background on the Primal Voidstone but it ends up replacing the entire block texture with the background. Would be nice if we could figure that out.

And that's about it for what I thought needed emissives. 

Finally, I suggest that we **Don't Merge** this pull request unless all the issues that exist are addressed. Alternatively, we can merge just the blocks that don't have any issues not and merge the rest later, once they are fixed.

### CODE REVIEW

**Comment by Liamdude** [comment]
These are quite good so far. As an initial matter, I do not think emissive textures ever show up in the inventory slots because of the ways that items render. I could be very wrong, but I haven't noticed anything doing it. I can check the Optifine issues to see if someone has ever brought it up before though.

One of the voidstones (second to the left in the bottom row) seems to have some of the non-rune parts of the block as emissive. To me, it looks off. I don't play with Chisel normally, but I will have to test this.

For the factory blocks, I will also have to check the texture to see what you are referring to regarding leaking. If some of the surrounding texture reflects that something is leaking out, that could likely be made emissive to show that detail.

For some reason, I am going in reverse order. Anyway, uranium is a tricky block material. I have had an inconsistent approach to it across mods (something I need to adjust again), but I would say that less is likely more for uranium. My current approach has been to only change greens that meet an arbitrary hue brightness, which I decide just by looking at them. With these blocks—for instance. the column second from the left—the darker section signifying depression would likely not be illuminated. Or we could take a more nuanced approach to apply emissiveness to the depressed sections that appear brighter (there are some bright stripes running through that section). Also, are the black parts of these blocks emissive here? If so, that would be unnecessary.

I will also look at the primal voidstone.

Whew, you have been fast to action. Thanks for that. I will try to test these soon.

**Comment by QuantumManiac** [comment]
Yes, you are correct about emissive textures not showing up for items in inventories and the likes. While this is the case, the emissives do show up when the items are outside of GUIs, e.g. dropped items, in-hand, and in item frames. Although I wouldn't imagine that adding emissives to items would add much, I just did it for consistency's sake. There are some cool things that emissive items can do though. My favourite is the AE2 Meteorite Compass - it's really nice to be able to see its needle when you're out exploring in the dark:
image

As for the Runed Primal Voidstone you mentioned, only the rune has emissives but the animated layer behind it is quite bright by itself. That's pretty much how it is with the unmodified textures.

As for the glowing vent factory block, here's a png of the texture along with the light seeping out
image
Yeah, I think that adding emissives to that area would be nice though, my attempts have left those regions looking way too bright:
image

That's a very good point for the uranium blocks though. It would probably be ideal to only add emissives to the brighter areas of the blocks, but at the same time it has to be done in a way that makes the emissives sort of "blend in" with the non-emissive parts of the texture. Kind of like my second attempt at the glowing vent above, it has to not look like there's an abrupt change between the lit-up and dark parts of the block. Is that even technically feasible, actually? I'll do some testing on that I guess. Lastly, the black parts on the uranium blocks are actually the metal frame part of the "Egregious" block and the metal support beams of the "Scaffold" block. You can see them in full brightness here:
image

**Comment by Liamdude** [comment]
I just did some testing. The primal voidstone background is unlikely to work. I believe Optifine's emissive textures work as a simple overlay that is given some lighting effects. Since there are two textures to make that block, Optifine is likely trying to make both things emissive at once, which causes the issue. That is just my guess, but I have no solutions for the problem.

I also just messed around with the factory vent. I was trying to make the emissive part animated while the original block is not. The result came out very poorly, so I do not think there is a good way to make the emissions be emissive without the vent looking weird.

So those two issues probably do not have solutions. Have you tested anything on the general uranium blocks? I feel like this is going to come down to whether to make the lighter or darker sections emissive. I feel like making the dark sections emissive has a certain appeal. Might bring them up to the level of the bright sections.

**Comment by QuantumManiac** [comment]
Yeah, it seems that the Primal Voidstone is a lost cause simply due to the limitations of Optifine. I'd imagine that the vent block has similar issues too. There being nothing emissives-wise in between no emissives at all and maximum lighting is quite a pain.

I'll take a look at the Uranium Blocks again sooner than later hopefully. I've not had too much time to do much with Minecraft but I'm expecting to get back into things in the next week or two.

**Pull request closed without merging**
